[telegram]
token = "1699062794:AAEjuMPyl6VZHqpEvec4i-PAx9sEITOjRk8"
workers = 1
admins = [563239385]
admins_only = false
maintenance_mode = false
persistent_temp_data = true

[pyrogram]
enabled = false
api_id = 3124686
api_hash = "9caf77bd10ed988695be467d34615674"

[sqlite]
filename = "stickersbot.sqlite"

[bot]
sourcecode = ""
issues = ""
channel = ""
